### ISSUE TITLE
"Disjunctive" questions are treated as booleans by the Question Classifier.

### ISSUE THREAD

**Issue by Josemvg** [librairy/MuHeQA#3]
Questions that use an "or", or "disjunctive" questions are answered as if they were booleans. For example, on the VANiLLA dataset there are up to 74 questions of this type, such as: "is thomas edison a male or female", "was andrea guerra a playmaker or defender on the pitch" or "is yakuza weapon from japan or china".
The performance of different models (i.e. (BERT, RoBERTa) on this type of questions should be revised.

**Comment by cbadenes** [comment]
Avoid boolean classification when question contains 'or'
